plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
    id 'com.google.android.libraries.mapsplatform.secrets-gradle-plugin'
}

android {

    namespace 'com.CannineShop.official'
    compileSdk 36

    defaultConfig {
        applicationId "com.CannineShop.official"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {

    // Firebase BOM (gestiona versiones automáticamente)
    implementation platform('com.google.firebase:firebase-bom:34.10.0')

    // Firebase
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-inappmessaging-display'
    implementation 'com.google.firebase:firebase-storage'

    // Google Services
    implementation 'com.google.android.gms:play-services-maps:20.0.0'
    implementation 'com.google.android.gms:play-services-auth:21.5.1'

    // AndroidX
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    // Material Design
    implementation 'com.google.android.material:material:1.13.0'

    // Kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.2.10"

    // Animaciones
    implementation 'com.airbnb.android:lottie:6.7.1'
    implementation 'com.cuberto:liquid-swipe:1.0.0'

    // PDF Viewer
    implementation 'com.github.barteksc:android-pdf-viewer:3.2.0-beta.1'

    // Dialog Loading
    implementation 'com.github.d-max:spots-dialog:1.1@aar'

    // Image Cropper
    implementation 'com.github.ArthurHub:Android-Image-Cropper:2.8.0'

    // Imagen perfil circular
    implementation 'de.hdodenhof:circleimageview:3.1.0'

    // Cargar imágenes
    implementation 'com.squareup.picasso:picasso:2.71828'

    // Tests
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'

}
